### ISSUE TITLE
script to setup virtualenv for python ML interface

### ISSUE THREAD

**Issue by Kallistos** [Kallistos/Distance-Based_Data#2]

**Comment by ChristianKaltenecker** [comment]
This issue is more related to SPL Conqueror.
The following lines work on my system:
```bash
virtualenv --python=python3 python-env
. ./python-env/bin/activate
pip3 install numpy scipy scikit-learn
``` 
Please try it out and tell me if it works for you too.

**Comment by ChristianKaltenecker** [comment]
Setting up the container as described above worked. 
Setting up the python environment is also handled in the Dockerfile of SPL Conqueror.
